name: Puzzles HQ workflow

on:
  release:
    types: [published, deleted]

jobs:
  publish-release:
    if: github.event.action == 'published'
    uses: PuzzlesHQ/.github/workflows/maven-publishing.yml@main
    secrets: inherit

  delete-release:
    if: github.event.action == 'deleted'
    uses: PuzzlesHQ/.github/workflows/maven-publishing.yml@main
    secrets: inherit
