name: Puzzles HQ workflow

on:
  release:
    types: [published, deleted]
env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  publish-release: 
    if: github.event.action == 'published'  
    uses: PuzzlesHQ/.github/workflows/maven-publishing.yml@main
    secrets: inherit
    with:
      group-id: com.puzzleshq
      artifact-id: access-writer

  delete-release:
    if: github.event.action == 'deleted'    
    uses: PuzzlesHQ/.github/workflows/maven-deleting.yml@main
    secrets: inherit
    with:
      group-id: ${{ vars.GROUP_ID }}
      artifact-id: CHANGE ME NOW!!!!!!
