name: Puzzles HQ workflow

on:
  release:
    types: [published, deleted]

jobs:
  publish-release: 
    if: github.event.action == 'published'
    runs-on: ubuntu-latest
    env:
      GITHUB_REF: ${{ github.ref }}
    
    uses: PuzzlesHQ/.github/workflows/maven-publishing.yml@main
    #uses: PuzzlesHQ/.github/workflows/maven-publishing-test.yml@main
    secrets: inherit

  delete-release:
    if: github.event.action == 'deleted'
    runs-on: ubuntu-latest
    env:
      GITHUB_REF: ${{ github.ref }}
    
    uses: PuzzlesHQ/.github/workflows/maven-publishing.yml@main
    #uses: PuzzlesHQ/.github/workflows/maven-publishing-test.yml@main
    secrets: inherit
