name: Puzzles HQ workflow

on:
  release:
    types: [published, deleted]
env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  publish-release: 
    if: github.event.action == 'published'  
    uses: PuzzlesHQ/.github/workflows/maven-publishing.yml@main
    #uses: PuzzlesHQ/.github/workflows/maven-publishing-test.yml@main
    secrets: inherit

  delete-release:
    if: github.event.action == 'deleted'    
    uses: PuzzlesHQ/.github/workflows/maven-publishing.yml@main
    #uses: PuzzlesHQ/.github/workflows/maven-publishing-test.yml@main
    secrets: inherit
