name: Deleting version on a Maven Repository

on:
  workflow_call:
    inputs:
        group-id:
          required: true
          type: string
        artifact-id:
          required: true
          type: string

jobs:
  deleting:
    runs-on: ubuntu-latest
    env:
      MAVEN_URL: ${{ vars.MAVEN_URL }}
      MAVEN_NAME: ${{ secrets.MAVEN_NAME }}
      MAVEN_SECRET: ${{ secrets.MAVEN_SECRET }}
      GROUP_ID: ${{ inputs.group-id }}
      ARTIFACT_ID: ${{ inputs.artifact-id }}
      VERSION: ${{ github.ref_name }}
    steps:
      - name: Check out PuzzlesHQ/.github
        uses: actions/checkout@v3
        with:
          repository: PuzzlesHQ/.github
          ref: main

      - name: Grant execute permission for gradlew
        run: chmod +x .github/scripts/move-version.sh

      - name: Move version from releases to archived
        run: .github/scripts/move-version.sh
