name: Publish project to Maven repository

on:
  workflow_call:
    inputs:
        group-id:
          required: false
          type: string
        artifact-id:
          required: false
          type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      MAVEN_NAME: ${{ secrets.MAVEN_NAME }}
      MAVEN_SECRET: ${{ secrets.MAVEN_SECRET }}
      MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      MAVEN_URL: ${{ vars.MAVEN_URL }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build project
        run: ./gradlew build

      - name: Publish to PuzzleHQsMaven
        if: ${{ env.MAVEN_NAME && env.MAVEN_SECRET && env.MAVEN_URL }}
        run: ./gradlew publishMavenPublicationToPuzzleHQsMavenRepository
        env:
          MAVEN_NAME: ${{ env.MAVEN_NAME }} # token secret (password)
          MAVEN_SECRET: ${{ env.MAVEN_SECRET }} # token secret (password)
          MAVEN_URL: ${{ env.MAVEN_URL }}
          GITHUB_REF: ${{ github.ref }}

      - name: Publish to Maven Central
        if: ${{ env.MAVEN_CENTRAL_USERNAME && env.MAVEN_CENTRAL_PASSWORD }}
        run: ./gradlew publishMavenPublicationToMavenLocal
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ env.MAVEN_CENTRAL_USERNAME }} # maven central username
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ env.MAVEN_CENTRAL_PASSWORD }} #  maven central password
          GITHUB_REF: ${{ github.ref }}
