name: Puzzles HQ workflow

on:
  release:
    types: [published]

jobs:
  publish-release:
    uses: PuzzlesHQ/.github/.github/workflows/maven-publishing.yml@main
    secrets: inherit
    with:
      TAG_NAME: ${{ github.event.release.tag_name }}
